fix: more human error messages
When running this application, some kind of error messages are not that clear, so this PR just handle the exceptions and provide a nice message to the user.

```
➜ uv run app.py init --source-dir ../chef-examples-berksfile/ "migration to ansible"
/home/eloy/dev/upstream/x2ansible/x2a-convertor/.venv/lib/python3.13/site-packages/ansible_risk_insight/loader.py:20: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
INFO:x2convertor.src.init: Analyzing repository for migration planning...
INFO:x2convertor.src.init: Creating migration agent
INFO:x2convertor.src.model: Initializing model: us.anthropic.claude-3-7-sonnet-20250219-v1:0
INFO:x2convertor.src.model: Using the 'bedrock_converse' provider with the 'us.anthropic.claude-3-7-sonnet-20250219-v1:0' model for accessing LLM
Error during migration planning: An error occurred (AccessDeniedException) when calling the Converse operation: Invalid API Key format: Must start with pre-defined prefix

Error: AWS Bedrock access denied.
Check your AWS credentials and IAM permissions.
Details: Invalid API Key format: Must start with pre-defined prefix
```

Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>